### PR TITLE
Fix problem with Document class and html() function

### LINKED ISSUE #18: Problem with Document class and html() function
### Version

1.0.3

### What did you expect to happen?

When parsing link and script elements was expecting to get back <?xml encoding="UTF-8"><link rel="stylesheet" 

### What actually happens?

Getting back <link rel="stylesheet"

### Steps to reproduce

Using Acorn prettify with clean-html5-markup.

### System info

The problem happens when using libxml2 Version (dotted): 2.15.1 on OS Linux.

### Log output

```shell
[24-Nov-2025 21:51:24 UTC] ========================================
[24-Nov-2025 21:51:24 UTC] 🔍 DEBUG STYLE TAG #1 - Handle: formidable
[24-Nov-2025 21:51:24 UTC] ========================================
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 📥 ORIGINAL HTML:
[24-Nov-2025 21:51:24 UTC] <link rel='stylesheet' id='formidable-css' href='https://stage.sarig.com/app/plugins/formidable/css/formidableforms.css?ver=11241526' media='all' />

[24-Nov-2025 21:51:24 UTC] Length: 149
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔧 STEP 1: Creating Document instance...
[24-Nov-2025 21:51:24 UTC] ✅ Document created successfully
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔧 STEP 2: Calling saveHTML()...
[24-Nov-2025 21:51:24 UTC] 📤 RAW saveHTML() output:
[24-Nov-2025 21:51:24 UTC] <!--?xml encoding="UTF-8"--><link rel="stylesheet" id="formidable-css" href="https://stage.sarig.com/app/plugins/formidable/css/formidableforms.css?ver=11241526" media="all">

[24-Nov-2025 21:51:24 UTC] Length: 175
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔬 FIRST 30 CHARACTERS (byte by byte):
[24-Nov-2025 21:51:24 UTC]   [ 0] ASCII  60 = "<"
[24-Nov-2025 21:51:24 UTC]   [ 1] ASCII  33 = "!"
[24-Nov-2025 21:51:24 UTC]   [ 2] ASCII  45 = "-"
[24-Nov-2025 21:51:24 UTC]   [ 3] ASCII  45 = "-"
[24-Nov-2025 21:51:24 UTC]   [ 4] ASCII  63 = "?"
[24-Nov-2025 21:51:24 UTC]   [ 5] ASCII 120 = "x"
[24-Nov-2025 21:51:24 UTC]   [ 6] ASCII 109 = "m"
[24-Nov-2025 21:51:24 UTC]   [ 7] ASCII 108 = "l"
[24-Nov-2025 21:51:24 UTC]   [ 8] ASCII  32 = " "
[24-Nov-2025 21:51:24 UTC]   [ 9] ASCII 101 = "e"
[24-Nov-2025 21:51:24 UTC]   [10] ASCII 110 = "n"
[24-Nov-2025 21:51:24 UTC]   [11] ASCII  99 = "c"
[24-Nov-2025 21:51:24 UTC]   [12] ASCII 111 = "o"
[24-Nov-2025 21:51:24 UTC]   [13] ASCII 100 = "d"
[24-Nov-2025 21:51:24 UTC]   [14] ASCII 105 = "i"
[24-Nov-2025 21:51:24 UTC]   [15] ASCII 110 = "n"
[24-Nov-2025 21:51:24 UTC]   [16] ASCII 103 = "g"
[24-Nov-2025 21:51:24 UTC]   [17] ASCII  61 = "="
[24-Nov-2025 21:51:24 UTC]   [18] ASCII  34 = """
[24-Nov-2025 21:51:24 UTC]   [19] ASCII  85 = "U"
[24-Nov-2025 21:51:24 UTC]   [20] ASCII  84 = "T"
[24-Nov-2025 21:51:24 UTC]   [21] ASCII  70 = "F"
[24-Nov-2025 21:51:24 UTC]   [22] ASCII  45 = "-"
[24-Nov-2025 21:51:24 UTC]   [23] ASCII  56 = "8"
[24-Nov-2025 21:51:24 UTC]   [24] ASCII  34 = """
[24-Nov-2025 21:51:24 UTC]   [25] ASCII  45 = "-"
[24-Nov-2025 21:51:24 UTC]   [26] ASCII  45 = "-"
[24-Nov-2025 21:51:24 UTC]   [27] ASCII  62 = ">"
[24-Nov-2025 21:51:24 UTC]   [28] ASCII  60 = "<"
[24-Nov-2025 21:51:24 UTC]   [29] ASCII 108 = "l"
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔧 STEP 3: Applying substr(saveHTML(), 23)...
[24-Nov-2025 21:51:24 UTC] ✂️  REMOVED (first 23 chars): '<!--?xml encoding="UTF-'
[24-Nov-2025 21:51:24 UTC] ✂️  REMAINING: 8"--><link rel="stylesheet" id="formidable-css" href="https://stage.sarig.com/app/plugins/formidable/css/formidableforms.css?ver=11241526" media="all">

[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔧 STEP 4: Calling Document::html() (substr + trim)...
[24-Nov-2025 21:51:24 UTC] 📤 FINAL OUTPUT:
[24-Nov-2025 21:51:24 UTC] 8"--><link rel="stylesheet" id="formidable-css" href="https://stage.sarig.com/app/plugins/formidable/css/formidableforms.css?ver=11241526" media="all">
[24-Nov-2025 21:51:24 UTC] Length: 151
[24-Nov-2025 21:51:24 UTC] 
[24-Nov-2025 21:51:24 UTC] 🔄 COMPARISON:
[24-Nov-2025 21:51:24 UTC]   Original length: 149
[24-Nov-2025 21:51:24 UTC]   Final length: 151
[24-Nov-2025 21:51:24 UTC]   Difference: -2 characters
[24-Nov-2025 21:51:24 UTC]   ⚠️  HTML WAS MODIFIED!
[24-Nov-2025 21:51:24 UTC]   🔴 FOUND "8\"-->" IN OUTPUT!
[24-Nov-2025 21:51:24 UTC]   Context: 8"--><link rel="stylesheet" id="formidable-css" href="https://stage.sa
[24-Nov-2025 21:51:24 UTC] ========================================
```

### Please confirm this isn't a support request.

Yes

### PR DESCRIPTION
**Pull request by dustingrofthenumber**
Resolves #18

### CODE REVIEW

File: src/Document.php [hunk 1]
```diff
@@ -69,7 +69,14 @@ public function xpath(string $expression): DOMNodeList
      */
     public function html(): string
     {
-        return trim(substr($this->document->saveHTML(), 23));
+        $html = $this->document->saveHTML();
+
+        // Remove XML declaration/comment that libxml2 may add
+        // Handles both <?xml encoding="UTF-8"> and any comments libxml2 adds
+        $html = preg_replace('/^<\?xml[^>]*>\s*/i', '', $html);
+        $html = preg_replace('/^<!--[^>]*-->\s*/', '', $html);
```
Comment (Log1x) [inline src/Document.php]: I'm seeing an issue with the regex for comments when the comment contains a `>` character.

```
> preg_replace('/^<!--[^>]*-->\s*/', '', '<!-- a > b -->');
= "<!-- a > b -->"

> preg_replace('/^<!--[^>]*-->\s*/', '', '<!-- a < b -->');
= ""
```

**Review by Log1x — CHANGES_REQUESTED** [review]
Appreciate the PR! Seeing an initial issue with the Regex for comments. Can we double check these handle every condition?

**Comment by davideprevosto** [comment]
I encountered the same problem; the code in the PR seems to solve my problem. Have you got any update on this?
Thank you!

**Comment by KristoferN** [comment]
Same problem on macOS with Herd PHP 8.3. libxml2 Version => 2.15.1

**Comment by Log1x** [comment]
> @Log1x should I switch approaches and commit it instead?

Sounds good to me! Appreciate it.

**Review by davideprevosto — COMMENTED** [review]
Not sure @dustingrofthenumber, but I think you should remove: 

`use Illuminate\Support\Str;`
